"""Tests of the report and the command line."""

from pathlib import Path

import pytest

from sbml2cellml.cellml import CellMLValidationError
from sbml2cellml.testsuite.cli import main
from sbml2cellml.testsuite.report import _reason, render_report, write_report
from sbml2cellml.testsuite.results import STAGES, CaseResult, StageResult, SuiteResult
from sbml2cellml.testsuite.runner import _message

FIXTURES = Path(__file__).parent / "data" / "testsuite" / "semantic"


def sample() -> SuiteResult:
    ok = {stage: StageResult("pass") for stage in STAGES}
    bad = dict(ok)
    bad["libopencor"] = StageResult("fail", "S1 exceeds the tolerance by 0.5", 0.5)
    bad["roundtrip"] = StageResult(
        "fail", "SimulationFailure: roadrunner: RuntimeError: x", None
    )
    bad2 = dict(ok)
    bad2["libopencor"] = StageResult("fail", "S2 exceeds the tolerance by 0.3", 0.3)
    return SuiteResult(
        "3.5.0",
        "0.1.0",
        {
            "00001": CaseResult("00001", ["Amount"], ["Compartment", "Species"], ok),
            "00002": CaseResult("00002", ["Amount"], ["Compartment"], bad),
            # a case whose model.m lists a tag twice (e.g. 01077); the tags
            # key must be deduplicated
            "00006": CaseResult("00006", ["Rate", "Rate"], ["Compartment"], bad2),
        },
        {"00003": "package comp", "00004": "package comp", "00005": "no L3V2 file"},
    )


def test_render_report() -> None:
    text = render_report(sample())
    assert text.startswith("<!-- generated by sbml2cellml-testsuite, do not edit -->")
    assert "# SBML test suite" in text
    assert "3.5.0" in text
    assert "0.1.0" not in text
    assert "| libopencor | 1 | 2 | 0 |" in text
    assert "numerical mismatch" in text
    assert "SimulationFailure: roadrunner: RuntimeError: x" in text
    assert "| package comp | 2 |" in text
    assert "| 00002 | Compartment | pass | pass | fail | pass | fail |" in text
    assert "—" not in text
    # the numerical mismatches of libopencor, grouped by tags
    assert "| Amount | 1 | 00002 |" in text
    # 00006 has the tag "Rate" twice; the key is deduplicated, not "Rate, Rate"
    assert "| Rate | 1 | 00006 |" in text
    assert "Rate, Rate" not in text


def test_reason_groups_tolerance_messages() -> None:
    a = _message(RuntimeError("S1 exceeds the tolerance by 0.5"))
    b = _message(RuntimeError("S2 exceeds the tolerance by nan"))
    assert _reason(a) == _reason(b) == "numerical mismatch"


def test_reason_groups_cellml_validation_messages() -> None:
    def message(cid: str, count: int) -> str:
        return _message(
            CellMLValidationError(
                f"CellML model 'case{cid}' converted from "
                f"'/home/mkoenig/.cache/sbml2cellml/sbml-test-suite/3.5.0/semantic/"
                f"{cid}/{cid}-sbml-l3v2.xml' has {count} errors:\n"
                "[ERROR] Math cn element with the attribute 'type' has an invalid value."
            )
        )

    a = message("00004", 8)
    b = message("00014", 12)
    assert _reason(a) == _reason(b)


def test_reason_handles_message_ending_with_error_marker() -> None:
    # "[ERROR]" with no text after it must not raise IndexError
    reason = _reason("CellMLValidationError: [ERROR]")
    assert isinstance(reason, str)
    assert reason == "CellMLValidationError:"


def test_render_report_groups_failure_reasons() -> None:
    ok = {stage: StageResult("pass") for stage in STAGES}
    variants = [
        ("00010", "S1 exceeds the tolerance by 0.5"),
        ("00011", "S1 exceeds the tolerance by 0.7"),
    ]
    cases = {}
    for cid, tolerance_message in variants:
        stages = dict(ok)
        stages["libopencor"] = StageResult("fail", tolerance_message, 0.5)
        cases[cid] = CaseResult(cid, ["Amount"], ["Compartment"], stages)
    validation = [
        (
            "00020",
            "CellML model 'case00020' converted from '/a/00020/00020-sbml-l3v2.xml' "
            "has 8 errors:\n[ERROR] Math cn element with the attribute 'type'.",
        ),
        (
            "00021",
            "CellML model 'case00021' converted from '/a/00021/00021-sbml-l3v2.xml' "
            "has 12 errors:\n[ERROR] Math cn element with the attribute 'type'.",
        ),
    ]
    for cid, validation_message in validation:
        stages = dict(ok)
        stages["sbml2cellml"] = StageResult(
            "fail", _message(CellMLValidationError(validation_message))
        )
        for stage in ("libopencor", "cellml2sbml", "roundtrip"):
            stages[stage] = StageResult("skip", "sbml2cellml failed")
        cases[cid] = CaseResult(cid, ["Amount"], ["Compartment"], stages)
    result = SuiteResult("3.5.0", "0.1.0", cases, {})
    text = render_report(result)
    assert "| numerical mismatch | 2 |" in text
    assert text.count("numerical mismatch") == 1
    assert "| CellMLValidationError: Math cn element with the attribute" in text
    assert text.count("CellMLValidationError: Math cn element with the attribute") == 1


def test_write_report(tmp_path: Path) -> None:
    path = tmp_path / "testsuite.md"
    write_report(sample(), path)
    assert path.read_text() == render_report(sample())


def test_cli_run_and_report(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    results = tmp_path / "results.json"
    report = tmp_path / "testsuite.md"
    code = main(
        [
            "run",
            "--suite-dir",
            str(FIXTURES),
            "--cases",
            "00001",
            "--work-dir",
            str(tmp_path / "work"),
            "--results",
            str(results),
            "--report",
            str(report),
        ]
    )
    assert code == 0
    assert results.is_file() and report.is_file()
    out = capsys.readouterr().out
    assert "00001" in out and "reference" in out
    report.unlink()
    assert main(["report", "--results", str(results), "--output", str(report)]) == 0
    assert report.is_file()


def test_cli_missing_results(tmp_path: Path) -> None:
    assert (
        main(
            [
                "report",
                "--results",
                str(tmp_path / "nope.json"),
                "--output",
                str(tmp_path / "r.md"),
            ]
        )
        == 1
    )
