"""Tests of the report and the command line."""

from pathlib import Path

import pytest

from sbml2cellml.testsuite.cli import main
from sbml2cellml.testsuite.report import render_report, write_report
from sbml2cellml.testsuite.results import STAGES, CaseResult, StageResult, SuiteResult

FIXTURES = Path(__file__).parent / "data" / "testsuite" / "semantic"


def sample() -> SuiteResult:
    ok = {stage: StageResult("pass") for stage in STAGES}
    bad = dict(ok)
    bad["libopencor"] = StageResult("fail", "S1 exceeds the tolerance by 0.5", 0.5)
    bad["roundtrip"] = StageResult(
        "fail", "SimulationFailure: roadrunner: RuntimeError: x", None
    )
    return SuiteResult(
        "3.5.0",
        "0.1.0",
        {
            "00001": CaseResult("00001", ["Amount"], ["Compartment", "Species"], ok),
            "00002": CaseResult("00002", ["Amount"], ["Compartment"], bad),
        },
        {"00003": "package comp", "00004": "package comp", "00005": "no L3V2 file"},
    )


def test_render_report() -> None:
    text = render_report(sample())
    assert text.startswith("<!-- generated by sbml2cellml-testsuite, do not edit -->")
    assert "# SBML test suite" in text
    assert "3.5.0" in text and "0.1.0" in text
    assert "| libopencor | 1 | 1 | 0 |" in text
    assert "S1 exceeds the tolerance" in text
    assert "SimulationFailure: roadrunner: RuntimeError: x" in text
    assert "| package comp | 2 |" in text
    assert "| 00002 | Compartment | pass | pass | fail | pass | fail |" in text
    assert "—" not in text


def test_write_report(tmp_path: Path) -> None:
    path = tmp_path / "testsuite.md"
    write_report(sample(), path)
    assert path.read_text() == render_report(sample())


def test_cli_run_and_report(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    results = tmp_path / "results.json"
    report = tmp_path / "testsuite.md"
    code = main(
        [
            "run",
            "--suite-dir",
            str(FIXTURES),
            "--cases",
            "00001",
            "--work-dir",
            str(tmp_path / "work"),
            "--results",
            str(results),
            "--report",
            str(report),
        ]
    )
    assert code == 0
    assert results.is_file() and report.is_file()
    out = capsys.readouterr().out
    assert "00001" in out and "reference" in out
    report.unlink()
    assert main(["report", "--results", str(results), "--output", str(report)]) == 0
    assert report.is_file()


def test_cli_missing_results(tmp_path: Path) -> None:
    assert (
        main(
            [
                "report",
                "--results",
                str(tmp_path / "nope.json"),
                "--output",
                str(tmp_path / "r.md"),
            ]
        )
        == 1
    )
