"""Tests of the report and the command line."""

from pathlib import Path

import pytest

from sbml2cellml.cellml import CellMLValidationError
from sbml2cellml.testsuite.cli import main
from sbml2cellml.testsuite.report import (
    TESTSUITE_FIGURE,
    _reason,
    render_report,
    tolerance_text,
    write_report,
)
from sbml2cellml.testsuite.results import STAGES, CaseResult, StageResult, SuiteResult
from sbml2cellml.testsuite.runner import _message

FIXTURES = Path(__file__).parent / "data" / "testsuite" / "semantic"


def sample() -> SuiteResult:
    ok = {stage: StageResult("pass") for stage in STAGES}
    bad = dict(ok)
    bad["libopencor"] = StageResult("fail", "S1 exceeds the tolerance by 0.5", 0.5)
    bad["roundtrip"] = StageResult(
        "fail", "SimulationFailure: roadrunner: RuntimeError: x", None
    )
    bad2 = dict(ok)
    bad2["libopencor"] = StageResult("fail", "S2 exceeds the tolerance by 0.3", 0.3)
    return SuiteResult(
        "3.5.0",
        "0.1.0",
        {
            "00001": CaseResult("00001", ["Amount"], ["Compartment", "Species"], ok),
            "00002": CaseResult("00002", ["Amount"], ["Compartment"], bad),
            # a case whose model.m lists a tag twice (e.g. 01077); the tags
            # key must be deduplicated
            "00006": CaseResult("00006", ["Rate", "Rate"], ["Compartment"], bad2),
        },
        {"00003": "package comp", "00004": "package comp", "00005": "no L3V2 file"},
    )


def test_render_report() -> None:
    text = render_report(sample())
    assert text.startswith("<!-- generated by sbml2cellml-testsuite, do not edit -->")
    assert "# SBML test suite" in text
    assert "3.5.0" in text
    assert "0.1.0" not in text
    # the total number of cases is the first number of a stage
    assert "| stage | total | pass | fail | skip | pass rate |" in text
    assert "| libopencor | 3 | 1 | 2 | 0 | 33.3% |" in text
    assert "### libopencor\n\n2 of 3 cases fail." in text
    assert "![" not in text
    # every failing case with its complete error, the mismatches in one group
    assert (
        "**2 cases, numerical mismatch**\n\n```text\n"
        "00002: S1 exceeds the tolerance by 0.5\n"
        "00006: S2 exceeds the tolerance by 0.3\n```" in text
    )
    assert (
        "**1 case**\n\n```text\n"
        "00002: SimulationFailure: roadrunner: RuntimeError: x\n```" in text
    )
    assert "| package comp | 2 |" in text
    assert "| 00002 | Compartment | pass | pass | fail | pass | fail |" in text
    assert "—" not in text
    # the numerical mismatches of libopencor, grouped by tags
    assert "| Amount | 1 | 00002 |" in text
    # 00006 has the tag "Rate" twice; the key is deduplicated, not "Rate, Rate"
    assert "| Rate | 1 | 00006 |" in text
    assert "Rate, Rate" not in text


def test_render_report_parameters() -> None:
    result = sample()
    result.cases["00001"].name = "Edelstein1996 - EPSP ACh event"
    text = render_report(
        result,
        title="BioModels",
        intro="Curated models.",
        command="sbml2cellml-biomodels",
        names=True,
    )
    assert text.startswith("<!-- generated by sbml2cellml-biomodels, do not edit -->")
    assert "# BioModels" in text and "Curated models." in text
    assert "| case | name | components |" in text
    assert "| 00001 | Edelstein1996 - EPSP ACh event | Compartment, Species |" in text


def test_render_report_informative_column() -> None:
    result = sample()
    result.cases["00001"].informative = True
    result.cases["00002"].informative = False
    text = render_report(result)
    assert (
        "| 00001 | Compartment, Species | pass | pass | pass | pass | pass | yes |"
        in text
    )
    assert "| 00002 | Compartment | pass | pass | fail | pass | fail | no |" in text
    # 00006's informative is left at its default (None): an empty cell
    assert "| 00006 | Compartment | pass | pass | fail | pass | pass |  |" in text


def test_render_report_informative_summary() -> None:
    # of the sample cases, only 00001 has a passing libopencor stage
    result = sample()
    result.cases["00001"].informative = True
    text = render_report(result)
    assert (
        "1 of the 1 cases with a passing libopencor stage are informative: "
        "the expected results move more than the tolerance band for at least "
        "one variable." in text
    )


def test_render_report_skips_informative_summary_without_passing_libopencor() -> None:
    stages = {stage: StageResult("pass") for stage in STAGES}
    stages["libopencor"] = StageResult("fail", "boom")
    result = SuiteResult(
        "3.5.0", "0.1.0", {"00001": CaseResult("00001", [], [], stages)}, {}
    )
    text = render_report(result)
    assert "cases with a passing libopencor stage are informative" not in text


def test_render_report_omits_tags_table_when_every_group_is_empty() -> None:
    # BioModels cases carry no test tags; a tags breakdown with a single
    # empty-string group says nothing and must not be rendered
    stages = {stage: StageResult("pass") for stage in STAGES}
    stages["libopencor"] = StageResult("fail", "S1 exceeds the tolerance by 0.5", 0.5)
    result = SuiteResult(
        "3.5.0", "0.1.0", {"BIOMD_A": CaseResult("BIOMD_A", [], [], stages)}, {}
    )
    text = render_report(result)
    assert "numerical mismatch" in text
    assert "| tags | cases | ids |" not in text


def test_render_report_escapes_pipe_in_case_name() -> None:
    result = sample()
    result.cases["00001"].name = "A | B"
    text = render_report(result, names=True)
    assert "A \\| B" in text


def test_render_report_escapes_pipe_in_skip_reasons() -> None:
    result = sample()
    result.skipped["00007"] = "reason | with a pipe"
    text = render_report(result)
    assert "| reason \\| with a pipe | 1 |" in text


def test_render_report_shows_errors_verbatim() -> None:
    # libopencor joins its issues with " | " and points at the code of a
    # compiler error; nothing is escaped, replaced or shortened in the block
    message = (
        "SimulationFailure: libopencor: SimulationError: instance: Task | Compiler: "
        "expression is not assignable:\n"
        "  298 |     rates[3] = --(0.00166112956810631*states[1])*constants[155];\n"
        "      |                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
        + ", ".join(f"'{k}'" for k in range(200))
    )
    result = sample()
    result.cases["00001"].stages["libopencor"] = StageResult("fail", message)
    text = render_report(result)
    first, *rest = message.split("\n")
    block = "\n".join([f"00001: {first}", *(f"    {line}" for line in rest)])
    assert f"```text\n{block}\n```" in text
    assert "'...'" not in text and "in total" not in text


def test_render_report_lists_every_case_of_a_group() -> None:
    ok = {stage: StageResult("pass") for stage in STAGES}
    cases = {}
    for k in range(25):
        stages = dict(ok)
        stages["roadrunner"] = StageResult(
            "fail", f"RuntimeError: The formula '0 = S{k}' is not supported."
        )
        cases[f"{k:05}"] = CaseResult(f"{k:05}", ["Amount"], ["Compartment"], stages)
    text = render_report(SuiteResult("3.5.0", "0.1.0", cases, {}))
    assert "**25 cases**" in text
    for k in range(25):
        assert f"{k:05}: RuntimeError: The formula '0 = S{k}' is not supported." in text


def test_render_report_documents_the_tolerances() -> None:
    text = render_report(sample())
    assert "`|value - expected| <= absolute + relative * |expected|`" in text
    assert "(relative/absolute `1e-9`/`1e-12`)" in text
    assert "repeated with `1e-8`/`1e-10` and `1e-7`/`1e-9`" in text
    assert "up to 100000 internal steps" in text
    assert "{solver}" not in text


def test_tolerance_text() -> None:
    assert tolerance_text(1e-9) == "1e-9"
    assert tolerance_text(1e-12) == "1e-12"
    assert tolerance_text(0.001) == "1e-3"
    assert tolerance_text(2.5e-4) == "2.5e-4"


def test_reason_groups_tolerance_messages() -> None:
    a = _message(RuntimeError("S1 exceeds the tolerance by 0.5"))
    b = _message(RuntimeError("S2 exceeds the tolerance by nan"))
    assert _reason(a) == _reason(b) == "numerical mismatch"


def test_reason_groups_cellml_validation_messages() -> None:
    def message(cid: str, count: int) -> str:
        return _message(
            CellMLValidationError(
                f"CellML model 'case{cid}' converted from "
                f"'/home/mkoenig/.cache/sbml2cellml/sbml-test-suite/3.5.0/semantic/"
                f"{cid}/{cid}-sbml-l3v2.xml' has {count} errors:\n"
                "[ERROR] Math cn element with the attribute 'type' has an invalid value."
            )
        )

    a = message("00004", 8)
    b = message("00014", 12)
    assert _reason(a) == _reason(b)
    # the further issues of a model do not split the group
    assert _reason(a + "\n[ERROR] Another issue.") == _reason(a)


def test_reason_handles_message_ending_with_error_marker() -> None:
    # "[ERROR]" with no text after it must not raise IndexError
    reason = _reason("CellMLValidationError: [ERROR]")
    assert isinstance(reason, str)
    assert reason == "CellMLValidationError:"


def test_render_report_groups_failure_reasons() -> None:
    ok = {stage: StageResult("pass") for stage in STAGES}
    variants = [
        ("00010", "S1 exceeds the tolerance by 0.5"),
        ("00011", "S1 exceeds the tolerance by 0.7"),
    ]
    cases = {}
    for cid, tolerance_message in variants:
        stages = dict(ok)
        stages["libopencor"] = StageResult("fail", tolerance_message, 0.5)
        cases[cid] = CaseResult(cid, ["Amount"], ["Compartment"], stages)
    validation = [
        (
            "00020",
            "CellML model 'case00020' converted from '/a/00020/00020-sbml-l3v2.xml' "
            "has 8 errors:\n[ERROR] Math cn element with the attribute 'type'.",
        ),
        (
            "00021",
            "CellML model 'case00021' converted from '/a/00021/00021-sbml-l3v2.xml' "
            "has 12 errors:\n[ERROR] Math cn element with the attribute 'type'.",
        ),
    ]
    for cid, validation_message in validation:
        stages = dict(ok)
        stages["sbml2cellml"] = StageResult(
            "fail", _message(CellMLValidationError(validation_message))
        )
        for stage in ("libopencor", "cellml2sbml", "roundtrip"):
            stages[stage] = StageResult("skip", "sbml2cellml failed")
        cases[cid] = CaseResult(cid, ["Amount"], ["Compartment"], stages)
    result = SuiteResult("3.5.0", "0.1.0", cases, {})
    text = render_report(result)
    assert "**2 cases, numerical mismatch**" in text
    assert text.count("**2 cases") == 2
    assert (
        "**2 cases**\n\n```text\n"
        "00020: CellMLValidationError: CellML model 'case00020' converted from "
        "'00020-sbml-l3v2.xml' has 8 errors:\n"
        "    [ERROR] Math cn element with the attribute 'type'.\n"
        "00021: CellMLValidationError: CellML model 'case00021' converted from "
        "'00021-sbml-l3v2.xml' has 12 errors:\n"
        "    [ERROR] Math cn element with the attribute 'type'.\n```" in text
    )


def test_render_report_figure() -> None:
    text = render_report(sample(), figure="images/testsuite.svg")
    alt = "Cases which pass, fail and skip the stages"
    assert f"![{alt}](images/testsuite.svg#only-light)" in text
    assert f"![{alt}](images/testsuite_dark.svg#only-dark)" in text


def test_write_report(tmp_path: Path) -> None:
    path = tmp_path / "testsuite.md"
    write_report(sample(), path)
    assert path.read_text() == render_report(sample())
    assert list(tmp_path.iterdir()) == [path]


def test_write_report_figure(tmp_path: Path) -> None:
    path = tmp_path / "testsuite.md"
    write_report(sample(), path, figure=TESTSUITE_FIGURE)
    assert path.read_text() == render_report(sample(), figure=TESTSUITE_FIGURE)
    assert (tmp_path / "images" / "testsuite.svg").is_file()
    assert (tmp_path / "images" / "testsuite_dark.svg").is_file()


def test_cli_run_and_report(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    results = tmp_path / "results.json"
    report = tmp_path / "testsuite.md"
    code = main(
        [
            "run",
            "--suite-dir",
            str(FIXTURES),
            "--cases",
            "00001",
            "--work-dir",
            str(tmp_path / "work"),
            "--results",
            str(results),
            "--report",
            str(report),
        ]
    )
    assert code == 0
    assert results.is_file() and report.is_file()
    figure = tmp_path / TESTSUITE_FIGURE
    assert figure.is_file()
    out = capsys.readouterr().out
    assert "00001" in out and "roadrunner" in out
    report.unlink()
    figure.unlink()
    assert main(["report", "--results", str(results), "--output", str(report)]) == 0
    assert report.is_file() and figure.is_file()


def test_cli_missing_results(tmp_path: Path) -> None:
    assert (
        main(
            [
                "report",
                "--results",
                str(tmp_path / "nope.json"),
                "--output",
                str(tmp_path / "r.md"),
            ]
        )
        == 1
    )
