"""Markdown report of a suite run, the page `docs/testsuite.md`."""

import re
from collections import Counter, defaultdict
from pathlib import Path

from sbml2cellml.testsuite.results import STAGES, SuiteResult

HEADER = "<!-- generated by sbml2cellml-testsuite, do not edit -->"
#: case ids listed per failure reason
CASES_PER_REASON = 10
#: length of a grouped failure reason
REASON_LENGTH = 120
#: quoted text, e.g. the model id and path of a CellMLValidationError
_QUOTED = re.compile(r"'[^']*'")
#: a number preceded by a space, `(`, `,` or `=`, so identifiers such as
#: `S1` are left untouched
_NUMBER = re.compile(r"(?<=[ (,=])[\d][\d.e+-]*")


def _reason(message: str) -> str:
    """Group key of a failure message.

    Args:
        message: a stage failure message.

    Returns:
        The message with quoted text replaced by `'...'`, numbers replaced
        by `N`, cut before ` by N` when present, whitespace collapsed and
        truncated to `REASON_LENGTH` characters, e.g.
        `S1 exceeds the tolerance by 0.5` becomes `S1 exceeds the tolerance`
        and two `CellMLValidationError` messages differing only in the model
        name, path and error count group into one row.
    """
    reason = _QUOTED.sub("'...'", message)
    reason = _NUMBER.sub("N", reason)
    reason = reason.split(" by N")[0]
    reason = " ".join(reason.split())
    return reason[:REASON_LENGTH]


def render_report(result: SuiteResult) -> str:
    """Render the report.

    Args:
        result: a suite run.

    Returns:
        The markdown page.
    """
    lines: list[str] = [
        HEADER,
        "# SBML test suite",
        "",
        f"Semantic test cases of the [SBML test suite](https://github.com/sbmlteam/sbml-test-suite) "
        f"{result.suite}, run with sbml2cellml {result.version}. Every case is simulated with "
        "roadrunner (`reference`), converted to CellML (`sbml2cellml`), simulated with libopencor "
        "(`libopencor`), converted back to SBML (`cellml2sbml`) and simulated with roadrunner again "
        "(`roundtrip`); every simulation is compared with the expected results using the tolerances "
        "of the case. See [Development](development.md#sbml-test-suite) for how to run it.",
        "",
        "## Summary",
        "",
        f"{len(result.cases)} cases run, {len(result.skipped)} skipped.",
        "",
        "| stage | pass | fail | skip | pass rate |",
        "| --- | --- | --- | --- | --- |",
    ]
    for stage in STAGES:
        counts = result.counts(stage)
        total = len(result.cases) or 1
        lines.append(
            f"| {stage} | {counts['pass']} | {counts['fail']} | {counts['skip']} | "
            f"{100 * counts['pass'] / total:.1f}% |"
        )

    lines += ["", "## Failure reasons", ""]
    for stage in STAGES:
        groups: dict[str, list[str]] = defaultdict(list)
        for cid, case in sorted(result.cases.items()):
            stage_result = case.stages[stage]
            if stage_result.status == "fail":
                groups[_reason(stage_result.message)].append(cid)
        if not groups:
            continue
        lines += [
            f"### {stage}",
            "",
            "| reason | cases | examples |",
            "| --- | --- | --- |",
        ]
        for reason, ids in sorted(
            groups.items(), key=lambda item: (-len(item[1]), item[0])
        ):
            examples = ", ".join(ids[:CASES_PER_REASON])
            more = f", ... ({len(ids)} in total)" if len(ids) > CASES_PER_REASON else ""
            lines.append(f"| {reason} | {len(ids)} | {examples}{more} |")
        lines.append("")

    lines += ["## Skipped cases", "", "| reason | cases |", "| --- | --- |"]
    for reason, count in sorted(Counter(result.skipped.values()).items()):
        lines.append(f"| {reason} | {count} |")

    lines += [
        "",
        "## Cases",
        "",
        "| case | components | " + " | ".join(STAGES) + " |",
        "| --- | --- | " + " | ".join("---" for _ in STAGES) + " |",
    ]
    for cid, case in sorted(result.cases.items()):
        statuses = " | ".join(case.stages[stage].status for stage in STAGES)
        lines.append(f"| {cid} | {', '.join(case.component_tags)} | {statuses} |")
    lines.append("")
    return "\n".join(lines)


def write_report(result: SuiteResult, path: Path) -> None:
    """Write the report.

    Args:
        result: a suite run.
        path: markdown file, overwritten.
    """
    Path(path).write_text(render_report(result), encoding="utf-8")
